#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/message

title "Lint commit message..."

## chore should no longer be allowed!
linting_errors="$(npm run commitlint; echo x$?)"

if [  ${linting_errors##*x} -ne 0 ]
then
  warning "Please adjust the commit message following the formatting rules"\
    "as documented in our contributing guidelines (CONTRIBUTING.md)."

  echo -e "\n\n${linting_errors%x*}"\
    "\nUse the following command to amend changes and edit the commit message."\
    "\n\n> git commit --amend\n"

  exit -1
fi

info "Commit message looks good"
