#!/usr/bin/env bash

set -e

FRONTEND_PORT="6006"

function waitForUrl() {
  until curl --output /dev/null --silent --head --fail "$1"; do
    sleep 2
  done
}

function teardown() {
  kill -9 "$FRONTEND_PID"
}

# start frontend
npm run storybook >/dev/null &
FRONTEND_PID="$!"
sleep 30 &
trap teardown EXIT

# wait for servers to start
waitForUrl "http://localhost:$FRONTEND_PORT"

# run tests
npx cypress run