name: UI Kit Code Checks
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
      - name: Install Dependencies 🔧
        run: npm install
      - name: Lint 🧹
        run: npm run lint
      - name: Build 🔨
        run: npm run dist
      - name: Unit Tests 🧪
        run: npm test
