name: Release
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
      - name: Install Dependencies 🔧
        run: npm install
      - name: Build Release
        run: npm run dist
      - name: Semantic Release ⬆️
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Storybook 📚
        run: |
          npm run build:storybook
      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook_static
          token: ${{ secrets.GITHUB_TOKEN }}
